id: IC326670C
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:12:36.761126'
last_modified: '2022-06-11T13:12:36.761131'
parser: null
source_metadata:
  title: Tsultrim Zangpo
  language: bo
  description: 'A series of texts by and about Tulku Tsultrim Zangpo (sprul sku tshul
    khrims bzang po, 1884–c.1957) alias Tulku Tsullo (sprul sku tshul lo) of Shukjung
    Monastery:'
  volume:
    f1AFF:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      base_file: f1AFF.txt
      order: 1
      parent: Dzogchen
    fFB17:
      title: The Four Uncommon Samayas of the Great Perfection
      base_file: fFB17.txt
      order: 2
      parent: Dzogchen
    f300B:
      title: A Simple Practice of Phowa, 'Transference of Consciousness'
      base_file: f300B.txt
      order: 3
      parent: Phowa
    fDAEC:
      title: 'A Shower of Blessings: A Sādhana of Blue-Green Tārā'
      base_file: fDAEC.txt
      order: 4
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
